owner: dingjiai
repo: status

sites:
  - name: 顶级AI 核心接口
    url: https://api.dingjiai.com/v1/models
    method: GET
    expectedStatusCodes:
      - 200
      - 401
      - 403

# 注意看下面，我把状态页配置删减到了最少，并且去掉了 cname
status-website:
  name: 顶级AI 运行状态墙
